AWS_ACCESS_KEY: "AKIAIZ5VRYG4UGKHIC4A"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "stoneflixter"
AWS_REGION: "us-east-1"

SECRET_KEY: sk_test_QZFch2tKkLbf4xiOMrbPEjgo
PUBLISHABLE_KEY: pk_test_Q52DwAl1J6V19JqEFXIWNJof